# Import Library

In [43]:
import seaborn as sns
import pandas as pd
import numpy as np
from pandas.api.types import is_numeric_dtype
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

# Load Dataset

In [44]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [45]:
df = sns.load_dataset("titanic")

In [46]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [47]:
df.shape

(891, 15)

In [48]:
df.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

# Data Preprocessing

In [49]:
df = df.drop(['deck'],axis=1)

In [50]:
df.duplicated().sum()

111

In [51]:
duplicet = df[df.duplicated(keep=False)]
duplicet

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,Queenstown,yes,True
29,0,3,male,NaN,0,0,7.8958,S,Third,man,True,Southampton,no,True
32,1,3,female,NaN,0,0,7.7500,Q,Third,woman,False,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True

In [52]:
df = df.drop_duplicates()

In [53]:
df.shape

(780, 14)

In [54]:
handle = df.age.mean()
handle

29.81275147928994

In [55]:
df.age = df.age.fillna(handle)

In [56]:
df['embarked'] = df['embarked'].bfill()

In [57]:
df['embarked'].unique()

<ArrowStringArray>
['S', 'C', 'Q']
Length: 3, dtype: str

In [58]:
df['embark_town'].unique()

<ArrowStringArray>
['Southampton', 'Cherbourg', 'Queenstown', nan]
Length: 4, dtype: str

In [59]:
df['embark_town'] = df['embark_town'].bfill()

In [60]:
df.isna().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
embark_town    0
alive          0
alone          0
dtype: int64

In [61]:
df1 = df.copy

# Encoding

In [62]:
le = LabelEncoder()

In [63]:
for col in df.columns:
    if not is_numeric_dtype(df[col]):
        df[col] = le.fit_transform(df[col])

In [64]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,True,2,0,False
1,1,1,0,38.0,1,0,71.2833,0,0,2,False,0,1,False
2,1,3,0,26.0,0,0,7.9250,2,2,2,False,2,1,True
3,1,1,0,35.0,1,0,53.1000,2,0,2,False,2,1,False
4,0,3,1,35.0,0,0,8.0500,2,2,1,True,2,0,True

# Feature Selection

In [65]:
X = df.drop(['survived'],axis=1)
y = df['survived']

In [66]:
X

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,3,1,22.000000,1,0,7.2500,2,2,1,True,2,0,False
1,1,0,38.000000,1,0,71.2833,0,0,2,False,0,1,False
2,3,0,26.000000,0,0,7.9250,2,2,2,False,2,1,True
3,1,0,35.000000,1,0,53.1000,2,0,2,False,2,1,False
4,3,1,35.000000,0,0,8.0500,2,2,1,True,2,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,3,0,39.000000,0,5,29.1250,1,2,2,False,1,0,False
887,1,0,19.000000,0,0,30.0000,2,0,2,False,2,1,True
888,3,0,29.812751,1,2,23.4500,2,2,2,False,2,0,False
889,1,1,26.000000,0,0,30.0000,0,0,1,True,0,1,True
890,3,1,32.000000,0,0,7.7500,1,2,1,True,1,0,True

In [67]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
887    1
888    0
889    1
890    0
Name: survived, Length: 780, dtype: int64

# Scaling

In [68]:
X = StandardScaler().fit_transform(X)

In [69]:
X

array([[ 8.82823175e-01,  7.73537753e-01, -5.70272253e-01, ...,
         5.88667683e-01, -8.38484805e-01, -1.14354375e+00],
       [-1.45936076e+00, -1.29276172e+00,  5.97607728e-01, ...,
        -1.89328255e+00,  1.19262746e+00, -1.14354375e+00],
       [ 8.82823175e-01, -1.29276172e+00, -2.78302258e-01, ...,
         5.88667683e-01,  1.19262746e+00,  8.74474632e-01],
       ...,
       [ 8.82823175e-01, -1.29276172e+00, -2.59321449e-16, ...,
         5.88667683e-01, -8.38484805e-01, -1.14354375e+00],
       [-1.45936076e+00,  7.73537753e-01, -2.78302258e-01, ...,
        -1.89328255e+00,  1.19262746e+00,  8.74474632e-01],
       [ 8.82823175e-01,  7.73537753e-01,  1.59652735e-01, ...,
        -6.52307433e-01, -8.38484805e-01,  8.74474632e-01]])

# Train Test Split

In [70]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [71]:
X_train

array([[ 8.82823175e-01, -1.29276172e+00, -2.10311473e+00, ...,
         5.88667683e-01,  1.19262746e+00, -1.14354375e+00],
       [ 8.82823175e-01, -1.29276172e+00, -2.59321449e-16, ...,
        -6.52307433e-01,  1.19262746e+00,  8.74474632e-01],
       [-1.45936076e+00,  7.73537753e-01,  6.70600226e-01, ...,
         5.88667683e-01, -8.38484805e-01,  8.74474632e-01],
       ...,
       [ 8.82823175e-01,  7.73537753e-01, -5.70272253e-01, ...,
         5.88667683e-01, -8.38484805e-01,  8.74474632e-01],
       [ 8.82823175e-01, -1.29276172e+00,  2.42242020e+00, ...,
         5.88667683e-01,  1.19262746e+00,  8.74474632e-01],
       [ 8.82823175e-01,  7.73537753e-01,  5.97607728e-01, ...,
         5.88667683e-01, -8.38484805e-01,  8.74474632e-01]])

In [72]:
X_train.shape

(585, 13)

In [73]:
X_test.shape

(195, 13)

# Model Build

In [74]:
model = RandomForestClassifier()

In [75]:
model.fit(X_train,y_train)

RandomForestClassifier()

In [76]:
pred = model.predict(X_test)
pred

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
      dtype=int64)

In [77]:
accuracy_score(y_test,pred)

1.0

In [78]:
model.score(X_train,y_train)

1.0

In [79]:
model.score(X_test,y_test)

1.0